version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: on-failure:5
    hostname: postgres
    environment:
      - POSTGRES_USER=sqlalchemy
      - POSTGRES_PASSWORD=sqlalchemy
      - POSTGRES_DB=nyc_taxi
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal

  mysql:
    container_name: mysql-db
    image: mysql:8.2
    hostname: mysql
    restart: always
    environment:
      - MYSQL_USER=sqlalchemy
      - MYSQL_PASSWORD=sqlalchemy
      - MYSQL_DATABASE=nyc_taxi
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - internal

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure:5
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - internal

networks:
  internal:
    name: pg-network
